apiVersion: argoproj.io/v1alpha1
kind: Application
metadata: 
  name: hello-node-argo
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/mufazzal/HelloNodeAutomation.git
    targetRevision: HEAD
    path: "Deployment/dev/k8sClusterDepAWSKOPS/modules"
    directory:
      recurse: true    
  destination:
    server: https://kubernetes.default.svc
    namespace: hello-node
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: false
---
# #argo CD is not working with ingress so commenting it now.
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: argocd
  name: argocd-server-ingress
  annotations:
    kubernetes.io/ingress.class: 'nginx'
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"   
    nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
#    nginx.ingress.kubernetes.io/use-regex: 'true'
#    nginx.ingress.kubernetes.io/rewrite-target: /$1
#    nginx.ingress.kubernetes.io/add-base-url: "true"
spec:
  rules:
    - host: 'cd.hn.com'
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: argocd-server
                port:
                  number: 80
