apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: HelloNode-Argo
  namespace: argocd
spec:
  project: HelloNode-Argo
  source:
    repoURL: https://github.com/mufazzal/HelloNodeAutomation.git
    targetRevision: HEAD
    path: guestbook
  destination:
    server: https://kubernetes.default.svc
    namespace: guestbook
