apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: my-standard-storage
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2
reclaimPolicy: Retain
allowVolumeExpansion: true
mountOptions:
  - debug
volumeBindingMode: Immediate
---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: hn-shared-pvc
#   namespace: hello-node
# spec:
#   accessModes:
#     - ReadWriteOnce
#   volumeMode: Filesystem
#   resources:
#     requests:
#       storage: 8Gi
#   storageClassName: my-standard-storage