pipeline {
    agent { label 'slave-ec2-fleet' }

    parameters {
        string(name: 'image', defaultValue: 'helloNode:latest', description: 'Please provide image for deployment')
    }        
    environment {
        awsCredId = "Mufazzal"
        gcServiceAccountFile = "gcServiceAccountFile-gke-hn"
        gkeProjectName = "hellonode-gke-343709"
        gkeClusterName = "hellonode-gke-343709-gke"
        gkeZone = "us-central1-b"
        CLOUDSDK_CORE_DISABLE_PROMPTS=1
    }
    stages {    

        stage('Initialize') {
           
            steps {
                 echo 'Creating Deployment in K8S'    
                
                sh """
                    printenv
                """              

                withCredentials([file(credentialsId: "$gcServiceAccountFile", variable: 'GC_KEY')]) {
                    sh """
                        source /home/ec2-user/google-cloud-sdk/path.bash.inc
                        source /home/ec2-user/google-cloud-sdk/completion.bash.inc
                        gcloud -v
                        kubectl version
                        gcloud auth activate-service-account --key-file=$GC_KEY
                        gcloud config set project $gkeProjectName
                        gcloud config set compute/zone $gkeZone
                        gcloud container clusters get-credentials $gkeClusterName
                    """
                }

                echo 'Creating Deployment in K8S'
            }
        } 
        stage('Deploying') {
            steps {
                 sh """
                 
                 """
            }      
        }
    } 
}
