apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-node-deployment
  namespace: hello-node
spec:
  selector:
    matchLabels:
      app: helloNode
  replicas: 2
  template:
    metadata:
      labels:
        app: helloNode
    spec:
      imagePullSecrets:
        - name: __ECR_SECRET_PLACEHOLDER__
      containers:
      - name: hello-node-container
        imagePullPolicy: Always
        image: '388412347424.dkr.ecr.us-east-1.amazonaws.com/hello-node-repo-ecr:Dockerizing-latest'
        ports:
        - containerPort: 3010
