apiVersion: argoproj.io/v1alpha1
kind: Application
metadata: 
  name: hello-node-argo
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/mufazzal/HelloNodeAutomation.git
    targetRevision: HEAD
    path: "Deployment/dev/k8sClusterDepAWSKOPS/helloNodeByNodePort"
  destination:
    server: https://api.hn.k8shn.com/
    namespace: hello-node
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
