apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: HelloNode-Argo
  namespace: argocd
spec:
  project: HelloNode-Argo
  source:
    repoURL: https://github.com/mufazzal/HelloNodeAutomation.git
    targetRevision: HEAD
    path: "Deployment/dev/k8sClusterDepAWSKOPS/helloNodeByNodePort"
  destination:
    server: https://kubernetes.default.svc
    namespace: hello-node
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
