apiVersion: v1
kind: Namespace
metadata:
  name: hello-node
  labels:
    istio-injection: enabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: hn-ms1
  labels:
    istio-injection: enabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: hn-ms2
  labels:
    istio-injection: enabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: hn-ms3
  labels:
    istio-injection: enabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: another-app
  labels:
    istio-injection: enabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: ingress-nginx
  labels:
    istio-injection: enabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager
  labels:
    istio-injection: enabled

    