apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: hn-ms1
  name: hn-ms1-ingress
  annotations:
    nginx.ingress.kubernetes.io/from-to-www-redirect: "true"
    kubernetes.io/ingress.class: 'nginx'
    nginx.ingress.kubernetes.io/use-regex: 'true'
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
    - host: 'api.hn.com'
      http:
        paths:
          - path: /hn-ms1/(.*)
            pathType: Prefix
            backend:
              service:
                name: hn-ms1-cluster-ip
                port:
                  number: 3050                             
