apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: hn-ms1-istio-vs
  namespace: hn-ms1
spec:
  hosts:
  - hn-ms1-cluster-ip
  - hn-ms1-cluster-ip.hn-ms1
  - hn-ms1-cluster-ip.hn-ms1.svc.cluster.local
  http:
  - route:
    - destination:
        host: hn-ms1-cluster-ip
    retries:
      attempts: 10
      perTryTimeout: 5s
      retryOn: 5xx,unavailable,cancelled,resource-exhausted,retriable-status-codes,reset      