apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-node-deployment
  namespace: hello-node
spec:
  selector:
    matchLabels:
      app: helloNode
  replicas: 2
  template:
    metadata:
      labels:
        app: helloNode
    spec:
      containers:
        - name: log-streaming-sidecar
          image: busybox
          args: ["/bin/sh", "-c", "tail", "-f", "/usr/src/logs/HelloNode/log.json"]
          
        - name: hello-node-container
          imagePullPolicy: Always
          image: 'mufazzal/hello-node:develop-42'
          env:
            - name: appEnv1
              value: valEnv1_fromdepfile
            - name: appEnv2
              value: valEnv2_fromdepfile
            - name: appEnv3
              value: valEnv3_fromdepfil
            - name: logDir
              value: "/usr/src/logs/HelloNode/log.json"

          # image: 'mufazzal/hello-node:develop-34'
          # image: '388412347424.dkr.ecr.us-east-1.amazonaws.com/hello-node-repo-ecr:Dockerizing-latest'
          ports:
            - containerPort: 3010
          volumeMounts:
            - name: config-map-volume
              mountPath: /usr/src/apps/HelloNode/runtimeConfigs/
            - name: log-volume-of-node
              mountPath: /usr/src/logs/HelloNode/              
            # - name: shred-disk
            #   mountPath: /usr/src/apps/HelloNode/hn_shared_disk/
          resources:
            requests:
              memory: "64Mi"
              cpu: "125m"
            limits:
              memory: "128Mi"
              cpu: "250m"            

      volumes:
        - name: log-volume-of-node
          emptyDir: {}      
        - name: config-map-volume
          configMap:
            name: config-map-hello-node
        # - name: shred-disk
        #   persistentVolumeClaim:
        #     claimName: hn-shared-pvc        
