apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-node-deployment
  namespace: hello-node
spec:
  selector:
    matchLabels:
      app: helloNode
  replicas: 2
  template:
    metadata:
      labels:
        app: helloNode
    spec:
      containers:
        - name: hello-node-container
          imagePullPolicy: Always
          image: 'mufazzal/hello-node:develop-38'
          env:
            - name: appEnv1
              value: valEnv1_fromdepfile
            - name: appEnv2
              value: valEnv2_fromdepfile
            - name: appEnv3
              value: valEnv3_fromdepfile
        
          # image: 'mufazzal/hello-node:develop-34'
          # image: '388412347424.dkr.ecr.us-east-1.amazonaws.com/hello-node-repo-ecr:Dockerizing-latest'
          ports:
            - containerPort: 3010
          volumeMounts:
            - name: config-map-volume
              mountPath: /usr/src/apps/HelloNode/runtimeConfigs/
            # - name: shred-disk
            #   mountPath: /usr/src/apps/HelloNode/hn_shared_disk/
      volumes:
        - name: config-map-volume
          configMap:
            name: config-map-hello-node
        # - name: shred-disk
        #   persistentVolumeClaim:
        #     claimName: hn-shared-pvc        