apiVersion: v1
kind: ConfigMap
metadata:
  name: config-map-hello-node
  namespace: hello-node
data:
  runConfigRaw: |
    runPropDef1=runPropDefVal1_fromConfigMap
    runPropDef2=runPropDefVal2_fromConfigMap
    runPropDef3=runPropDefVal3_fromConfigMap
  # configMapKey1: "White"
  # configMapKey2: "summer"
