apiVersion: v1
kind: Service
metadata:
  name: hello-node-cluster-ip
  namespace: hello-node
spec:
  type: ClusterIP
  selector:
    app: helloNode
  ports:
    - port: 3020        # Used in multip client system
      targetPort: 3010  # The EXPOSE port of container
      # nodePort: 32100
