apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hn-pvc
  namespace: hello-node
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 8Gi
  storageClassName: hn-standard-storage