pipeline {
    agent { label 'slave-ec2-fleet' }

    parameters {
        string(name: 'image', defaultValue: 'helloNode:latest', description: 'Please provide image for deployment')
        string(name: 'kubectlVersion', defaultValue: '1.22.0-00', description: 'Version of kubectl')
    }        
    environment {
        nameSpace = "hello-node"
    }
    stages {    

        stage('Installing KubeCtl') {
            steps {
                echo "Installing Kubectl Version $kubectlVersion"
                sh """
                    curl -LO https://dl.k8s.io/release/$kubectlVersion/bin/linux/amd64/kubectl
                    sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
                    chmod +x kubectl
                    mkdir -p ~/.local/bin
                    mv ./kubectl ~/.local/bin/kubectl
                    export PATH=~/.local/bin:$PATH
                    source ~/.bash_profile
                """
            }      
        }

        stage('Fetcing KubeConfig') {
            steps {
                echo "copying kubeconfig from S3"
                sh """
                    aws s3 cp "s3://hello-node-repo-bucket/BareMetalK8sCluster/Master/kubeconfig" .
                    cat kubeconfig
                """
            }      
        }
        stage('Deployment') {
           
            steps {
                echo 'Creating Deployment in K8S'    
                

                echo 'Creating Deployment in K8S'
            }
        } 
        
    } 
}

