pipeline {
    agent { label 'slave-ec2-fleet' }

    parameters {
        string(name: 'image', defaultValue: 'helloNode:latest', description: 'Please provide image for deployment')
    }        
    environment {
        nameSpace = "hello-node"
    }
    stages {    

        stage('Fetcing KubeConfig') {
            steps {
                echo "scp and copying the kubeconfig"
                withCredentials([sshUserPrivateKey(credentialsId: "K8SMasterNodeSSHKey", keyFileVariable: 'keyfile')]) {
                    sh """
                        ls
                        pwd
                        echo $keyfile
                    """
                }
            }      
        }
        stage('Deployment') {
           
            steps {
                echo 'Creating Deployment in K8S'    
                

                echo 'Creating Deployment in K8S'
            }
        } 
        
    } 
}

