apiVersion: argoproj.io/v1alpha1
kind: Application
metadata: 
  name: hello-node-argo
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/mufazzal/HelloNodeAutomation.git
    targetRevision: HEAD
    path: "Deployment/dev/k8sClusterDepAWSKOPS/helloNode"
  destination:
    server: https://kubernetes.default.svc
    namespace: hello-node
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: argocd
  name: ingress-service
  annotations:
    kubernetes.io/ingress.class: 'nginx'
    nginx.ingress.kubernetes.io/use-regex: 'true'
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"    
spec:
  rules:
    - http:
        paths:
          - path: /cd?(.*)
            pathType: Prefix
            backend:
              service:
                name: argocd-server
                port:
                  number: 443    